[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scholarscout"
version = "1.0.0"
description = "AI Research Assistant"
dependencies = []

# Dependencies are managed via requirements.txt